// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKDjZ-f2KQQhHgL7mn0Moa3eruBpQgOhs',
    appId: '1:59157593289:web:ec68abb6578645e357e118',
    messagingSenderId: '59157593289',
    projectId: 'todoproject-363d6',
    authDomain: 'todoproject-363d6.firebaseapp.com',
    databaseURL: 'https://todoproject-363d6-default-rtdb.firebaseio.com',
    storageBucket: 'todoproject-363d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIdzxmTw5koKrf3M0a8ozJ2qQa0lela4',
    appId: '1:59157593289:android:2ed08f3e2d382df957e118',
    messagingSenderId: '59157593289',
    projectId: 'todoproject-363d6',
    databaseURL: 'https://todoproject-363d6-default-rtdb.firebaseio.com',
    storageBucket: 'todoproject-363d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChYt3tUGjAEUIzGBfHlPctfyg65jCPijc',
    appId: '1:59157593289:ios:16cc4faf06aa500657e118',
    messagingSenderId: '59157593289',
    projectId: 'todoproject-363d6',
    databaseURL: 'https://todoproject-363d6-default-rtdb.firebaseio.com',
    storageBucket: 'todoproject-363d6.appspot.com',
    iosBundleId: 'com.example.todoonlineapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChYt3tUGjAEUIzGBfHlPctfyg65jCPijc',
    appId: '1:59157593289:ios:16cc4faf06aa500657e118',
    messagingSenderId: '59157593289',
    projectId: 'todoproject-363d6',
    databaseURL: 'https://todoproject-363d6-default-rtdb.firebaseio.com',
    storageBucket: 'todoproject-363d6.appspot.com',
    iosBundleId: 'com.example.todoonlineapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKDjZ-f2KQQhHgL7mn0Moa3eruBpQgOhs',
    appId: '1:59157593289:web:0ed488e59a73feba57e118',
    messagingSenderId: '59157593289',
    projectId: 'todoproject-363d6',
    authDomain: 'todoproject-363d6.firebaseapp.com',
    databaseURL: 'https://todoproject-363d6-default-rtdb.firebaseio.com',
    storageBucket: 'todoproject-363d6.appspot.com',
  );

}